import { CommandRegistry } from "./CommandRegistry";
import { CommandType } from "./Command";
import { PingCommand } from "@commands/PingCommand";
import { EchoCommand } from "@commands/EchoCommand";
import { GetCommand } from "@commands/GetCommand";
import { SetCommand } from "@commands/SetCommand";
import { DelCommand } from "@commands/DelCommand";
import { ExistsCommand } from "@commands/ExistsCommand";
import { LPushCommand } from "@commands/LPushCommand";
import { RPushCommand } from "@commands/RPushCommand";
import { LPopCommand } from "@commands/LPopCommand";
import { RPopCommand } from "@commands/RPopCommand";
import { LLenCommand } from "@commands/LLenCommand";
import { LIndexCommand } from "@commands/LIndexCommand";
import { LRangeCommand } from "@commands/LRangeCommand";
import { BLPopCommand } from "@commands/BLPopCommand";
import { SubscribeCommand } from "@commands/SubscribeCommand";
import { PublishCommand } from "@commands/PublishCommand";
import { UnSubscribeCommand } from "@commands/UnSubscribeCommand";
import { XAddCommand } from "@commands/XaddCommand";
import { XRangeCommand } from "@commands/XRangeCommand";

export const registerCommands = (registry: CommandRegistry): void => {
  registry.register(CommandType.PING, new PingCommand());
  registry.register(CommandType.ECHO, new EchoCommand());
  registry.register(CommandType.GET, new GetCommand());
  registry.register(CommandType.SET, new SetCommand());
  registry.register(CommandType.DEL, new DelCommand());
  registry.register(CommandType.EXISTS, new ExistsCommand());
  registry.register(CommandType.LPUSH, new LPushCommand());
  registry.register(CommandType.RPUSH, new RPushCommand());
  registry.register(CommandType.LPOP, new LPopCommand());
  registry.register(CommandType.RPOP, new RPopCommand());
  registry.register(CommandType.LLEN, new LLenCommand());
  registry.register(CommandType.LINDEX, new LIndexCommand());
  registry.register(CommandType.LRANGE, new LRangeCommand());
  registry.register(CommandType.BLPOP, new BLPopCommand());
  registry.register(CommandType.SUBSCRIBE, new SubscribeCommand());
  registry.register(CommandType.PUBLISH, new PublishCommand());
  registry.register(CommandType.UNSUBSCRIBE, new UnSubscribeCommand());
  registry.register(CommandType.XADD, new XAddCommand());
  registry.register(CommandType.XRANGE, new XRangeCommand());
};
